openapi: 3.0.3
info:
  title: Event Relation Detection API
  description: Extract event relations from sentences
  version: 1.0.11
paths:
  /extract:
    get:
      summary: Perform event relation detection
      parameters:
        - in: query
          name: st0
          required: true
          schema:
            type: string
            default: roberta_st0_best_model_st1.pt
            enum:
              - roberta_st0_best_model_st1.pt
          description: Subtask 0 - Sentence Classification model(filter out sentences with no event relations)
        - in: query
          name: st1
          required: true
          schema:
            type: string
            default: roberta_st1_best_model
            enum:
              - roberta_st1_best_model
              - rebel_st3_model_our_data_gpt_augmented.pth
              - zephyr
              - dpo
              - una
              - solar
              - gpt4
              - off
          description: Subtask 2 - Relation Classification model or `off` to skip the subtask
        - in: query
          name: st2
          required: true
          schema:
            type: string
            default: roberta_st2_epoch_9
            enum:
              - roberta_st2_epoch_9
              - rebel_st3_model_our_data_gpt_augmented.pth
              - zephyr
              - dpo
              - una
              - solar
              - gpt4
              - off
          description: Subtask 2 - Relation Extration model (extract the word spans referring to events and relations) or `off` to skip the subtask
        - in: query
          name: api
          required: False
          schema:
            type: string
            default:
          description: OpenAI API key (only if you are using GPT-4)
        - in: query
          name: f
          required: false
          schema:
            type: string
            default: test.csv
            enum:
              - test.csv
          description: File on which to perform the event relation extraction. `f` or `q` are mandatory
        - in: query
          name: q
          required: false
          schema:
            type: string
            default:
          description: Sentence to analyse to find the event relation. `f` or `q` are mandatory
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                properties:
                  label: 
                    type: string
                    example: cause
                    description: relation label between "cause", "intend", "enable", "prevent"
                  num_rs: 
                    type: integer
                    example: 1
                    description: number of found relations
                  span_pred: 
                    type: string
                    description: the annotated string
                  st0_model: 
                    type: string
                    description: model used for sub-task 0
                  st1_model: 
                    type: string
                    description: model used for sub-task 1
                  st2_model: 
                    type: string
                    description: model used for sub-task 2
                  text:
                    description: the original string
              example:
                - label: cause
                  num_rs: 1
                  span_pred: 'At Balagangamanahalli panchayat in Dharmapuri , <ARG1>residents of Eechampatti
                    village laid siege to the Nallampalli BDO s office <SIG0>in protest</ARG1></SIG0>
                    against <ARG0>non supply of water</ARG0> . '
                  st0_model: roberta
                  st1_model: roberta
                  st2_model: roberta
                  text: 'At Balagangamanahalli panchayat in Dharmapuri , residents of Eechampatti
                    village laid siege to the Nallampalli BDO s office in protest against non supply
                    of water . '

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /models:
    get:
      summary: Return the list of available models for each sub-task
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                properties:
                  st0:
                    type: array
                  st1:
                    type: array
                  st2:
                    type: array
                  f:
                    type: array
              example:
                f:
                - test.csv
                st0:
                - roberta_st0_best_model_st1.pt
                st1:
                - roberta_st1_best_model
                - rebel_st3_model_our_data_gpt_augmented.pth
                - zephyr
                - dpo
                - una
                - solar
                - gpt4
                - 'off'
                st2:
                - roberta_st2_epoch_9
                - rebel_st3_model_our_data_gpt_augmented.pth
                - zephyr
                - dpo
                - una
                - solar
                - gpt4
                - 'off'


