FROM python:3.11-alpine

ADD requirements.demo.txt requirements.txt

RUN pip install -r requirements.txt
ENV WANDB_MODE=disabled

ADD streamlit_app.py .
EXPOSE 5004

CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "5004"]